@Api_HostAddress = http://localhost:5000

POST {{Api_HostAddress}}/chat
Accept: application/json
Content-Type: application/json

{
  "stream": false,
  "messages": [
    {
      "role": "user",
      "content": "tell me a joke"
    }
  ]
}


###

POST {{Api_HostAddress}}/agent
Accept: application/json
Content-Type: application/json

{
  "stream": true,
  "messages": [
    {
      "role": "user",
      "content": "tell me a joke"
    },
    {
      "role": "assistant",
      "content": "Why don’t skeletons fight each other?  \nThey don’t have the guts!"
    },
    {
      "role": "user",
      "content": "another joke"
    }
  ]
}
