@Api_HostAddress = http://localhost:5000

POST {{Api_HostAddress}}/chat
Accept: application/json
Content-Type: application/json

{
  "systemMessage": "start setences with: I'm NexAI",
  "message": "tell me a joke?",
  "stream": false
}

###

POST {{Api_HostAddress}}/agent
Accept: application/json
Content-Type: application/json

{
  "stream": true,
  "messages": [
    {
      "role": "user",
      "content": "tell me a joke"
    },
    {
      "role": "assistant",
      "content": "Why don’t skeletons fight each other?  \nThey don’t have the guts!"
    },
    {
      "role": "user",
      "content": "another"
    }
  ]
}
