using System.Text.Json.Serialization;

namespace NexAI.Zendesk.Api.Dtos;

public record TicketDto(
    [property: JsonPropertyName("url")]
    string? Url,
    [property: JsonPropertyName("id")]
    long? Id,
    [property: JsonPropertyName("external_id")]
    string? ExternalId,
    [property: JsonPropertyName("via")]
    object? Via,
    [property: JsonPropertyName("created_at")]
    string? CreatedAt,
    [property: JsonPropertyName("updated_at")]
    string? UpdatedAt,
    [property: JsonPropertyName("generated_timestamp")]
    long? GeneratedTimestamp,
    [property: JsonPropertyName("type")]
    string? Type,
    [property: JsonPropertyName("subject")]
    string? Subject,
    [property: JsonPropertyName("raw_subject")]
    string? RawSubject,
    [property: JsonPropertyName("description")]
    string? Description,
    [property: JsonPropertyName("priority")]
    string? Priority,
    [property: JsonPropertyName("status")]
    string? Status,
    [property: JsonPropertyName("recipient")]
    string? Recipient,
    [property: JsonPropertyName("requester_id")]
    long? RequesterId,
    [property: JsonPropertyName("submitter_id")]
    long? SubmitterId,
    [property: JsonPropertyName("assignee_id")]
    long? AssigneeId,
    [property: JsonPropertyName("organization_id")]
    long? OrganizationId,
    [property: JsonPropertyName("group_id")]
    long? GroupId,
    [property: JsonPropertyName("collaborator_ids")]
    long[]? CollaboratorIds,
    [property: JsonPropertyName("follower_ids")]
    long[]? FollowerIds,
    [property: JsonPropertyName("email_cc_ids")]
    long[]? EmailCcIds,
    [property: JsonPropertyName("forum_topic_id")]
    long? ForumTopicId,
    [property: JsonPropertyName("problem_id")]
    long? ProblemId,
    [property: JsonPropertyName("has_incidents")]
    bool? HasIncidents,
    [property: JsonPropertyName("is_public")]
    bool? IsPublic,
    [property: JsonPropertyName("due_at")]
    string? DueAt,
    [property: JsonPropertyName("tags")]
    string[]? Tags,
    [property: JsonPropertyName("custom_fields")]
    TicketDto.CustomField[]? CustomFields,
    [property: JsonPropertyName("satisfaction_rating")]
    object? SatisfactionRating,
    [property: JsonPropertyName("sharing_agreement_ids")]
    long[]? SharingAgreementIds,
    [property: JsonPropertyName("custom_status_id")]
    long? CustomStatusId,
    [property: JsonPropertyName("encoded_id")]
    string? EncodedId,
    [property: JsonPropertyName("fields")]
    object[]? Fields,
    [property: JsonPropertyName("followup_ids")]
    long[]? FollowupIds,
    [property: JsonPropertyName("ticket_form_id")]
    long? TicketFormId,
    [property: JsonPropertyName("brand_id")]
    long? BrandId,
    [property: JsonPropertyName("allow_channelback")]
    bool? AllowChannelback,
    [property: JsonPropertyName("allow_attachments")]
    bool? AllowAttachments,
    [property: JsonPropertyName("from_messaging_channel")]
    bool? FromMessagingChannel,
    [property: JsonPropertyName("assignee_email")]
    string? AssigneeEmail,
    [property: JsonPropertyName("attribute_value_ids")]
    long[]? AttributeValueIds,
    [property: JsonPropertyName("collaborators")]
    object[]? Collaborators,
    [property: JsonPropertyName("comment")]
    object? Comment,
    [property: JsonPropertyName("email_ccs")]
    object? EmailCcs,
    [property: JsonPropertyName("followers")]
    object? Followers,
    [property: JsonPropertyName("macro_id")]
    long? MacroId,
    [property: JsonPropertyName("macro_ids")]
    long[]? MacroIds,
    [property: JsonPropertyName("metadata")]
    object? Metadata,
    [property: JsonPropertyName("requester")]
    object? Requester,
    [property: JsonPropertyName("safe_update")]
    bool? SafeUpdate,
    [property: JsonPropertyName("updated_stamp")]
    string? UpdatedStamp,
    [property: JsonPropertyName("via_followup_source_id")]
    long? ViaFollowupSourceId,
    [property: JsonPropertyName("via_id")]
    long? ViaId,
    [property: JsonPropertyName("voice_comment")]
    object? VoiceComment)
{
    public record CustomField(
        [property: JsonPropertyName("id")]
        long? Id,
        [property: JsonPropertyName("value")]
        object? Value);
}